name: c
description: C-md, Library of Defining & parsing for Dart CLI Commands & Arguments
version: 0.0.3
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.4 <3.0.0"
  # dependencies:
  #   path: ^1.8.0

dev_dependencies:
  test: ^1.21.4
  mockito: ^5.3.0
  build_runner: ^2.2.0
#   lints: ^1.0.0
